/** Shared reservation category labels for non-state-specific bucket codes. */
export const CATEGORY_LABEL_BY_CODE: Record<string, string> = {
  open: "Open",
  sc: "SC",
  st: "ST",
  obc: "OBC",
  mbc: "MBC",
  sebc: "SEBC",
  ews: "EWS",
  st_special: "ST Special",
  obc_m: "OBC-M",
  obc_mp: "OBC-MP",
  st_and_sa: "ST & SA",
  obc_and_mbc: "OBC & MBC",
  pwd: "PwD",
  pwd_open: "PwD Open",
  pwd_sc: "PwD SC",
  pwd_st: "PwD ST",
  pwd_obc: "PwD OBC",
  pwd_ews: "PwD EWS",
  sainik: "Sainik",
  ff: "Freedom Fighters",
  gs: "Govt School",
  vj: "VJ",
  nt: "NT (B/C/D)",
  def: "Defence",
  seb: "SEBC (Maratha)",
  mk: "MKB / border",
};
